# Generated by Django 5.2.6 on 2025-10-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_useremailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
