# Generated by Django 5.2.6 on 2025-11-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='profile.png', null=True, upload_to='profile'),
        ),
    ]
