# Generated by Django 5.2.6 on 2025-12-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='profile/profile.png', null=True, upload_to='profile'),
        ),
    ]
