# Generated by Django 5.2.6 on 2025-12-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_notification_user_alter_notification_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('FulFilled', 'FulFilled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100),
        ),
    ]
