# Generated by Django 5.2.6 on 2025-12-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_color_color_code_alter_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default='category/category.png', null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(blank=True, default='products/product.png', null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='products/product.png', null=True, upload_to='products'),
        ),
    ]
